export const CLOCK_TOGGLE_START = 'CLOCK_TOGGLE_START';
export const CLOCK_TOGGLE_MODE = 'CLOCK_TOGGLE_MODE';
export const CLOCK_UPDATE_TIME_LEFT = 'CLOCK_UPDATE_TIME_LEFT';
export const CLOCK_UPDATE_INTERVAL_ID = 'CLOCK_UPDATE_INTERVAL_ID';