export const CLOCK_SWITCH_MODE = 'CLOCK_SWITCH_MODE';
export const CLOCK_TOGGLE_START = 'CLOCK_TOGGLE_START';
export const CLOCK_UPDATE_SUMMARY = 'CLOCK_UPDATE_SUMMARY';
export const CLOCK_UPDATE_TIME_LEFT = 'CLOCK_UPDATE_TIME_LEFT';
export const CLOCK_UPDATE_TIMER_SETTING = 'CLOCK_UPDATE_TIMER_SETTING';
export const CLOCK_UPDATE_ALARM_SOUND_TEMP = 'CLOCK_UPDATE_ALARM_SOUND';
export const CLOCK_UPDATE_TICKING_SPEED_TEMP = 'CLOCK_UPDATE_TICKING_SPEED';
