export const REPORT_GET_SESSIONS = 'REPORT_GET_SESSIONS';
export const REPORT_ADD_SESSION = 'REPORT_ADD_SESSION';
export const REPORT_SWITCH_REPORT_MODE = 'REPORT_SWITCH_REPORT_MODE';
export const REPORT_UPDATE_TOTAL_SUB_SESSIONS = 'REPORT_UPDATE_TOTAL_SUB_SESSIONS';
