export const REPORT_SWITCH_REPORT_MODE = 'REPORT_SWITCH_REPORT_MODE';
export const REPORT_GET_SESSIONS_IN_PERIOD = 'REPORT_GET_SESSIONS_IN_PERIOD';
export const REPORT_UPDATE_TOTAL_SUB_SESSIONS =
  'REPORT_UPDATE_TOTAL_SUB_SESSIONS';
