export const SUMMARY_GET_INFO = 'SUMMARY_GET_INFO';
export const SUMMARY_UPDATE_INFO = 'SUMMARY_UPDATE_INFO';
export const SUMMARY_GET_INFO_FAILED = 'SUMMARY_GET_INFO_FAILED';
export const SUMMARY_SWITCH_REPORT_MODE = 'SUMMARY_SWITCH_REPORT_MODE';
