export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_GET_USER_INFO = 'USER_GET_USER_INFO';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_UPDATE_USER_INFO = 'USER_UPDATE_USER_INFO';