"""empty message

Revision ID: 2882cdf55bdb
Revises: 502cdef5cbdf
Create Date: 2022-03-13 23:18:53.971466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2882cdf55bdb'
down_revision = '502cdef5cbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
