"""empty message

Revision ID: 7084f06c019e
Revises: 15455e4ccf7c
Create Date: 2022-03-24 16:25:43.051457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7084f06c019e'
down_revision = '15455e4ccf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'finished_at')
    # ### end Alembic commands ###
