"""empty message

Revision ID: 8910fc38ce0d
Revises: ba7f3b469486
Create Date: 2022-04-07 20:04:38.210495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910fc38ce0d'
down_revision = 'ba7f3b469486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
