"""empty message

Revision ID: aab2292d2d5f
Revises: 7084f06c019e
Create Date: 2022-03-24 16:26:30.074848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab2292d2d5f'
down_revision = '7084f06c019e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
