"""add column long_break_interval for timer table

Revision ID: d9933c9a56b9
Revises: 5a29cd551543
Create Date: 2021-12-22 10:55:37.659080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9933c9a56b9'
down_revision = '5a29cd551543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('long_break_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'long_break_interval')
    # ### end Alembic commands ###
